### ISSUE TITLE
P.63 リスト4.12について

### ISSUE THREAD

**Issue by kaitokimuraofficial** [yuuu/aws_ruby_serverless_book_site#3]
本書63ページ中のリスト4.12にて
`notify-for-working/record_working/Gemfile`となっておりますが、
正しくは、`notify-for-working/notify_working/Gemfile`ではないでしょうか。

ご確認お願いいたします。

**Comment by yuuu** [comment]
@kaitokimuraofficial 
こちら、ご連絡ありがとうございます。
ご指摘の通り、誤記がありご迷惑をおかけいたしました。
[正誤表](https://github.com/yuuu/aws_ruby_serverless_book_site?tab=readme-ov-file#%E6%AD%A3%E8%AA%A4%E8%A1%A8) にも追記させていただきました。
